<?php

echo $this->translate->_('Books');
echo $this->translate->_('Create');
echo $this->translate->_('Navigation');
echo $this->translate->_('User Management');
echo $this->translate->_('Groups Management');
echo $this->translate->_('Groups Permission');
echo $this->translate->_('System Administration');
echo $this->translate->_('Logout');
echo $this->translate->_('Action Management');
echo $this->translate->_('Add new');
echo $this->translate->_('Save');
echo $this->translate->_('Update');
echo $this->translate->_('Save change');
echo $this->translate->_('Clear cache');
echo $this->translate->_('All');
echo $this->translate->_('Today');
echo $this->translate->_('Category');
echo $this->translate->_('Content');
echo $this->translate->_('An error occurred');
echo $this->translate->_('Application error');
echo $this->translate->_('Exception information');
echo $this->translate->_('Message');
echo $this->translate->_('Request parameters');
echo $this->translate->_('Page not found');






?>
