
        <script type="text/javascript">
                $(".pagination li.none").click(function() {
                    $("#window-loading").show();
                    $("#window-loading #loading").show();
                });

                $("#w-loading").click(function() {
                    $("#window-loading").show();
                    $("#window-loading #loading").show();
                });
        </script>
        <footer class="footer">
            <div class="container">
                <p>&copy; Design by Duong The email <a href="mailto:mr.theak007@gmail.com">Mr.theak007@gmail.com</a>. <?php echo $this->translate('All rights reserved.') ?></p>                                    
            </div>
        </footer>        
    </body>  
</html>