<?php
$filename = APPLICATION_PATH . "/../public/templates/admin-metro/admin.ini";
$config = new Zend_Config_Ini($filename, "template");

$templateUrl = $this->baseUrl() . $config->url;
$cssUrl = $templateUrl . $config->dirCss;
$jsUrl = $templateUrl . $config->dirJs;
//$imgUrl = $templateUrl . $config->dirImg;

$title = $config->title;
$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->baseUrl() . $config->url . '/favicon.ico'));

if (count($config->metaHttp) > 0) {
    foreach ($config->metaHttp as $key => $value) {
        $tmp = explode("|", $value);
        $this->headMeta()->appendHttpEquiv($tmp[0], $tmp[1]);
    }
}

if (count($config->metaName) > 0) {
    foreach ($config->metaName as $key => $value) {
        $tmp = explode("|", $value);
        $this->headMeta()->appendName($tmp[0], $tmp[1]);
    }
}

if (count($config->fileCss) > 0) {
    foreach ($config->fileCss as $key => $css) {
        $this->headLink()->appendStylesheet($cssUrl . $css, 'screen');
    }
}

if (count($config->fileJs) > 0) {
    foreach ($config->fileJs as $key => $js) {
        $this->headScript()->appendFile($jsUrl . $js, 'text/javascript');
    }
}
?>

<?php echo $this->doctype(); ?>  
<html>  
    <head>                  
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>        
        <?php
        $this->headScript()->prependFile('/public/editor/ckeditor/ckeditor.js')
                ->prependFile('/public/editor/ckfinder/ckfinder.js');
        ?>
        <?php echo $this->headLink() ?>  
        <?php echo $this->headStyle() ?>  
        <?php echo $this->headScript() ?> 
                 
    </head>  
    <body>        
        <header class="header">
            <h2 class="title-p">
                <a href="<?php echo $this->baseUrl() . '/admin' ?>"><?php echo $title; ?></a>
            </h2>
            <span class="user">
                <?php
                $auth = Zend_Auth::getInstance();
                if ($auth->hasIdentity()) {
                    ?>
                    <?php echo $auth->getIdentity()->username . ","; ?>
                    <a href="<?php echo $this->baseUrl() . '/admin/login/logout' ?>"><?php echo $this->translate->_("Logout"); ?></a>
                <?php } ?>
            </span>
            <div class="navigation-head">
                <?php
                $menu = $this->navigation()->menu();
                $vertical = $menu->setUlClass('navigation-hozital');
                echo $vertical;
                ?>

            </div>

            <?php
            $lang = Zend_Registry::get('locale');
            //$lang = Zend_Translate::getCache();
            //echo $lang->getIds();
            ?>
            <div class="lang">
                <span id="lang-vi" <?php if ($lang == "vi_VN") echo 'class="active"'; ?>><img src="<?php echo $this->baseUrl() . '/public/templates/admin-metro/img/lang/vi.png'; ?>"/></span> | <span id="lang-en" <?php if ($lang == "en_US") echo 'class="active"'; ?>><img src="<?php echo $this->baseUrl() . '/public/templates/admin-metro/img/lang/uk.png'; ?>"/></span>
            </div>
            <div id="clock"></div>
            <script>
                $(document).ready(function() {
                    $("#lang-vi").click(function() {
                        var url = '<?php echo $this->baseUrl . "/admin/language/vi"; ?>';
                        $.ajax({
                            url: url,
                            success: function() {
                                window.location.reload();
                            }
                        });

                    });
                    $("#lang-en").click(function() {
                        var url = '<?php echo $this->baseUrl . "/admin/language/en"; ?>';
                        $.ajax({
                            url: url,
                            success: function() {
                                window.location.reload();
                            }
                        });

                    });
                });
            </script>
        </header>
        <div class="linear">

        </div>