
<table class="table table-striped table-bordered">
    <tr>
        <th>Module</th>
        <th>Controller</th>
        <th>Action</th>        
        <th>Note</th>
        <th></th>
    </tr>
    <?php
    if ($this->list != null) {
        foreach ($this->list as $item) {
            ?>
            <tr>
                <td><?php echo $item['module']; ?></td>
                <td><?php echo $item['controller'] ?></td>            
                <td><?php echo $item['action'] ?></td>            
                <td><?php echo $item['description'] ?></td>        
                <td>
                    <a href="<?php echo $this->currentController . '/edit/id/' . $item['id']; ?>"><i class="icon-pencil"></i></a>
                    <a href="#" id="delete" onclick="check_del(<?php echo $item['id']; ?>);"><i class="icon-trash"></i></a>
                </td>
            </tr>
            <?php
        }
    }
    ?>



</table>

<?php
if ($this->paginator) {
    echo $this->paginationControl($this->paginator, 'Sliding', 'extends/paginator.phtml');
}
?>

