<table class="table table-striped table-bordered">
    <tr>
        <th>Name</th>
        <th>Descriptions</th>
        <th>Groups Parent</th>        
    </tr>
    <?php
    if ($this->list != null) {
        $group = new Nop_Db_Table_AuthGroup();
        foreach ($this->list as $item) {
            if ($item['group_parent_id'] != null) {
                $info = $group->getGroup($item['group_parent_id']);
            }
            ?>
            <tr>
                <td><a href="<?php echo $this->url(array("action" => "get", "id" => $item['id'])); ?>"><?php echo $item['name']; ?></a></td>
                <td><?php echo $item['description'] ?></td>
                <td>
                    <?php
                    if (isset($info)) {
                        echo $info['name'];
                    }
                    ?>
                </td>            
            </tr>
            <?php
        }
    }
    ?>



</table>