
<div class="demo-section">
    <?php
    if ($this->update != null) {
        ?>
        <p><?php echo $this->update; ?>. <a href="<?php echo $this->currentController ?>"><?php echo $this->translate->_("Back"); ?></a></p>
    <?php } ?>
    <h3><?php echo $this->user['username'] ?></h3>
    <?php echo $this->form; ?>            

</div>
<div class="console"></div>

<script type="text/javascript">
    window.onload = function() {
        var required = $("#required").kendoMultiSelect().data("kendoMultiSelect");
        var add = "<?php echo $this->currentController . '/add' ?>";
        var id = "<?php echo $this->user['id'] ?>";
        $("#get").click(function() {
            var value = required.value();
            $.ajax({
                type: 'POST',
                url: add,
                data: ({value: value, id: id}),
                success: function() {
                    kendoConsole.log("Cập nhật thành công!");
                }
            });
        });
    };
</script>