<table class="table table-striped table-bordered">
    <tr>
        <th>Name</th>
        <th>First name</th>
        <th>Last name</th>        
        <th>Email</th>
        <th>Status</th>
        <th>Supper Admin</th>
        <th></th>
    </tr>
    <?php
    if ($this->list != null) {
        foreach ($this->list as $item) {
            ?>
            <tr>
                <td><a href="<?php echo $this->url(array("action" => "get", "id" => $item['id'])) ?>"><?php echo $item['username']; ?></a></td>
                <td><?php echo $item['first_name'] ?></td>
                <td><?php echo $item['last_name'] ?></td>            
                <td><?php echo $item['email'] ?></td>   
                <td>
                    <?php if ($item['is_active'] == 1) { ?>
                        <p class="right" onclick="status(<?php echo $item['id'] ?>);"><i id="img-status<?php echo $item['id'] ?>" class="front-on"></i></p>
                    <?php } elseif ($item['is_active'] == 0) { ?>
                        <p class="right" onclick="status(<?php echo $item['id'] ?>);"><i id="img-status<?php echo $item['id'] ?>" class="front-off"></i></p>
                    <?php } ?>
                </td>
                <td>
                    <?php if ($item['is_super_admin'] == 1) { ?>
                        <p class="right" onclick="admin(<?php echo $item['id'] ?>);"><i id="img-admin<?php echo $item['id'] ?>" class="front-on"></i></p>
                    <?php } elseif ($item['is_super_admin'] == 0) { ?>
                        <p class="right" onclick="admin(<?php echo $item['id'] ?>);"><i id="img-admin<?php echo $item['id'] ?>" class="front-off"></i></p>
                    <?php } ?>
                </td>
                <td>
                    <a href="<?php echo $this->currentController . '/edit/id/' . $item['id']; ?>"><i class="icon-pencil"></i></a>
                    <span id="delete" onclick="check_del(<?php echo $item['id']; ?>);"><i class="icon-trash"></i></span>
                </td>
            </tr>
            <?php
        }
    }
    ?>



</table>

<script type="text/javascript">
                function status(id) {
                    var onoff = '<?php echo $this->baseUrl() . $this->currentController . "/active"; ?>';
                    $(document).ready(function() {
                        $.ajax({
                            type: 'POST',
                            url: onoff,
                            data: {id: id},
                            success: result
                        });
                        function result(data) {
                            //alert(data);
                            if (data['active'] === 'off') {
                                $('#img-status' + id).removeClass('front-on');
                                $('#img-status' + id).addClass('front-off');
                            }
                            if (data['active'] === 'on') {
                                $('#img-status' + id).removeClass('front-off');
                                $('#img-status' + id).addClass('front-on');
                            }
                        }
                    });
                }

                function admin(id) {
                    var onoff = '<?php echo $this->baseUrl() . $this->currentController . "/supper-admin"; ?>';
                    $(document).ready(function() {
                        $.ajax({
                            type: 'POST',
                            url: onoff,
                            data: {id: id},
                            success: result
                        });
                        function result(data) {
                            //alert(data);
                            if (data['active'] === 'off') {
                                $('#img-admin' + id).removeClass('front-on');
                                $('#img-admin' + id).addClass('front-off');
                            }
                            if (data['active'] === 'on') {
                                $('#img-admin' + id).removeClass('front-off');
                                $('#img-admin' + id).addClass('front-on');
                            }
                        }
                    });
                }
</script>